---
title: "Home Page for Enformer Human and Rat Cross-species Analysis"
descriptions: Updates, links to analysis in the rat project
format: html
---

## Updates this Week

* [Resolved founder VCF issues with multiallelic sites with `*` in ALT column](https://sabrina-dl.hakyimlab.org/posts/2023-09-12-processing-hs-founder-rat-genotypes/)
    * Two types of mutations at one site: deletion (`*`) and alternative allele
    * Dropped deletions, kept alternative allele genotype data
* [Submitted jobs for Enformer genome-wide prediction on 8 founder rats](https://sabrina-dl.hakyimlab.org/posts/2023-11-07-hs-founder-epigenomes/pipeline)
* [Submitted jobs for Enformer runs across Br rat population for 490 genes](https://sabrina-dl.hakyimlab.org/posts/2023-11-02-br-personalized-prediction-additional-genes/pipeline)
    * We currently have [cross-population performance results](https://sabrina-dl.hakyimlab.org/posts/2023-08-31-br-personalized-prediction-on-more-genes/) for 868 genes
* [Started Br individual haplotype probabilities from 8 founder rats](https://sabrina-dl.hakyimlab.org/posts/2023-11-08-calculating-Br-genotype-probabilities/)
    * Downloaded genetic mapping files and split by chromosome
    * I'm currently trying to install all dependencies: pysam, qtl2 (R)
* Applied for SDSC's Expanse HPC compute resources

## Introduction

### Data Inventory

* Genotype and gene expression data for 340 rats in the Br study
    * Mean gene expression used as ground truth reference gene expression
* GTEx gene expression data used as ground truth reference gene expression
* Rat reference genome as input to Enformer to predict reference gene expression 
* Human reference genome as input to Enformer to predict reference gene expression

### Goals

* Determine whether Enformer models (human and mouse) can predict expression across genes
* Use genotypes to predict gene expression in the Br rats with the Enformer models


## Correlation across genes

We are currently using the CAGE:Brain human track at a gene's TSS to estimate gene expression in rats. For all GTEx gene expression comparisons, we used mean TPM in brain cortex tissue. We want to make 3 types of comparison:

1. $\rho^h_{Hh}$: Correlation between human reference gene expression predicted with Enformer human head and GTEx mean gene expression
2. $\rho^h_{Rr}$: Correlation between rat reference gene expression predicted with Enformer human head and Br reference gene expression
3. $\rho^h_{HR}$: Correlation between rat reference gene expression and human reference gene expression

Enformer is optimized to predict variation across the genome, so we use $\rho^h_{Hh}$ as the baseline performance. Intuitively, we hope to see $\rho^h_{Rr} = \rho^h_{HR} \rho^h_{Hh}$.

[Personal transcriptome variation is poorly explained by current genomic deep learning models, Huang et al](https://www.biorxiv.org/content/10.1101/2023.06.30.547100v1.full.pdf) performed the same analysis on GEUVADIS LCL gene expression data and found a correlation of 0.57

### Analysis Summary


1. [$\rho^h_{Hh} = 0.539$](https://sabrina-dl.hakyimlab.org/posts/2023-08-22-correlation-between-enformer-and-gtex-expression-across-genes-by-chromosome/)
2. [$\rho^h_{Rr} = 0.453$](https://sabrina-dl.hakyimlab.org/posts/2023-08-22-correlation-across-rn7-genes-by-chromosome/)
3. [$\rho^h_{HR} = 0.886$](https://sabrina-dl.hakyimlab.org/posts/2023-09-01-comparing-human-vs-rat-mean-expression-across-genes)

Other analysis includes: 
1. Validating Huang et al.'s [correlation of 0.57](https://sabrina-dl.hakyimlab.org/posts/2023-09-06-validating-Huang-et-al) in human LCL tissues, I even obtained a higher correlation of 0.77 when I included all GEUVADIS genes

## Correlation across individuals

I added support for unphased VCFs, which cuts the number of Enformer runs in half by averaging the two haplotypes. I also added options to output mouse head predictions or both.

* [Results for 868 genes selected for significant eQTLs and observed variation](https://sabrina-dl.hakyimlab.org/posts/2023-08-31-Br-personalized-prediction-on-more-genes/)


