---
title: Plotting Br Rats' Haplotype Distributions
author: Sabrina Mi, Dan Munro
date: 12/13/2023
---

```{r libraries}
library(ggplot2)
library(tidyr)
library(stringr)

```


```{r calc_genoprob to df function}

reshape_genoprob <- function(sample, prob) {
  sample_prob <- as.data.frame(t(prob[[1]][sample, , ]))
  snps <- str_split(rownames(sample_prob), ":", simplify = TRUE)
  colnames(snps) <- c("chrom", "pos")
  sample_prob <- cbind(sample_prob, snps)
  plot_df <- pivot_longer(sample_prob, cols = -c(chrom, pos), names_to = "Strain", values_to = "prob")
  plot_df$pos <- as.integer(plot_df$pos)
  return(plot_df)
}

```


### Samples Plots

```{r}
chr20_prob <- readRDS("/Users/sabrinami/chr20-qtl2-outputs/batch0_prob.rds")
chr19_prob <- readRDS("/Users/sabrinami/chr19-qtl2-outputs/batch0_prob.rds")
samples <- sample(rownames(chr20_prob[[1]])
for (sample in samples, size = 2, replace = FALSE)) {
  chr20_df <- reshape_genoprob(sample, chr20_prob)
  chr19_df <- reshape_genoprob(sample, chr19_prob)
  df <- rbind(chr19_df, chr20_df)
  plot <- df %>% ggplot(aes(x = pos, y = prob, fill = Strain)) +
    facet_wrap(~ chrom, ncol = 2, dir = "v", strip.position = "left") +
    geom_area() +
    scale_fill_brewer(type = "qual", palette = 6) +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    theme_bw() +
    xlab("Position (Mb)") +
    ylab("Estimated Proportion") +
    ggtitle(paste0("Br Sample: ", sample)) +  
    theme(
        axis.text.y = element_blank(),
        panel.grid = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.x = element_line(size = 0.25),
        panel.border = element_blank(),
        strip.background = element_blank(),
        legend.position = "top",
    )
    print(plot)
    ggsave(paste0(sample,".png"), plot = plot, width = 8, height = 6, units = "in", dpi = 300)
}

```